language: node_js
node_js:
  - "10"

services:
  - docker

git:
  submodules: false

addons:
  apt:
    packages:
      - libgconf-2-4

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  
before_install:
  - git submodule update --init

cache: yarn

install: yarn
script:
  - yarn lint
  - docker-compose up -d elasticsearch redis
  - make fs bundle fe
  - make fs build-api build-ui fe
  - make fs start-api es-restore start-ui fe
  - sleep 5
  - make fs ci fe
  - docker-compose down -v elasticsearch redis
