version: '3.4'
services:
  elasticsearch:
    build: vue-storefront-api/docker/elasticsearch/
    volumes:
      - ./vue-storefront-api/docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - esdat1:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'

  storefront-api:
    build:
      context: vue-storefront-api
      dockerfile: docker/vue-storefront-api/Dockerfile
    env_file: vue-storefront-api/docker/vue-storefront-api/default.env
    environment:
      VS_ENV: dev
    ports:
      - '8080:8080'
    volumes:
      - './API/config.json:/var/www/config/local.json'
      - './API/payment-klarna:/var/www/src/api/extensions/payment-klarna'
      - './API/payment-klarna-example:/var/www/src/api/extensions/payment-klarna-example'

  storefront-ui:
    build:
      context: vue-storefront
      dockerfile: docker/vue-storefront/Dockerfile
      network: host
    env_file: vue-storefront/docker/vue-storefront/default.env
    environment:
      VS_ENV: dev
    ports:
      - '3000:3000'
    volumes:
      - './frontend/config.json:/var/www/config/local.json'
      - './frontend/theme:/var/www/src/themes/default'
      - './frontend/modules.ts:/var/www/src/modules/index.ts'
      - './frontend/payment-klarna:/var/www/src/modules/payment-klarna'
