version: '3.4'
services:
  api:
    depends_on:
      - elasticsearch
      - redis
    tmpfs:
      - /var/www/dist
    volumes:
      - './.docker/vue-storefront-api/config:/var/www/config'
      - './.docker/vue-storefront-api/ecosystem.json:/var/www/ecosystem.json'
      - './.docker/vue-storefront-api/migrations:/var/www/migrations'
      - './.docker/vue-storefront-api/package.json:/var/www/package.json'
      - './.docker/vue-storefront-api/babel.config.js:/var/www/babel.config.js'
      - './.docker/vue-storefront-api/tsconfig.json:/var/www/tsconfig.json'
      - './.docker/vue-storefront-api/nodemon.json:/var/www/nodemon.json'
      - './.docker/vue-storefront-api/scripts:/var/www/scripts'
      - './.docker/vue-storefront-api/src:/var/www/src'
      - './.docker/vue-storefront-api/var:/var/www/var'

  ui:
    tmpfs:
      - /var/www/dist
    volumes:
      - './.docker/vue-storefront/babel.config.js:/var/www/babel.config.js'
      - './.docker/vue-storefront/config:/var/www/config'
      - './.docker/vue-storefront/core:/var/www/core'
      - './.docker/vue-storefront/ecosystem.json:/var/www/ecosystem.json'
      - './.docker/vue-storefront/.eslintignore:/var/www/.eslintignore'
      - './.docker/vue-storefront/.eslintrc.js:/var/www/.eslintrc.js'
      - './.docker/vue-storefront/lerna.json:/var/www/lerna.json'
      - './.docker/vue-storefront/tsconfig.json:/var/www/tsconfig.json'
      - './.docker/vue-storefront/tsconfig-build.json:/var/www/tsconfig-build.json'
      - './.docker/vue-storefront/shims.d.ts:/var/www/shims.d.ts'
      - './.docker/vue-storefront/package.json:/var/www/package.json'
      - './.docker/vue-storefront/src:/var/www/src'
      - './.docker/vue-storefront/var:/var/www/var'
      - './.docker/vue-storefront/packages:/var/www/packages'
      - '/var/www/dist'

  elasticsearch:
    volumes:
      - esdat1:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"

volumes:
  esdat1:
